### PR TITLE
test(voice): resolve the feature path once instead of in 22 suites (#521)

### LINKED ISSUE #521: test(voice): hoist FEATURE_PATH + cucumber loader to shared __tests__/helpers
## Description

Four vitest-cucumber test files now independently resolve the same 4-hop relative path to \`specs/voice-agents.feature\` and call \`loadFeature\` separately:

- \`javascript/src/voice/__tests__/voice-contract-surface.test.ts\` (PR #517, merged)
- \`javascript/src/voice/__tests__/stt.test.ts\` (PR #513)
- \`javascript/src/voice/__tests__/tts.test.ts\` (PR #513)
- \`javascript/src/voice/__tests__/transcribe.test.ts\` (PR #513)

## Context

If the test layout shifts or the feature file moves, all four paths must be updated. Hoisting \`FEATURE_PATH\` and a shared \`loadFeature\` invocation to \`javascript/src/voice/__tests__/_helpers.ts\` (or similar) eliminates the duplication. Could also hoist \`makeMockOpenAI\` / \`OpenAILike\` helpers used in multiple files.

## Scope

- Add a single helper module exporting \`FEATURE_PATH\` (and optionally a memoized \`feature\` promise).
- Update all four test files to import from it.

PR #515 will add at least one more retrofit test file, so doing this before #515 lands keeps the count from growing.

Surfaced by /review on PR #513. Reviewer convergence: principles + hygiene.

Related: #516, #517, #513.

---
*Classification: Refactor*
*Status: stub — investigation pending. Issue is not-ready until \`/investigate\` completes.*

### PR DESCRIPTION
**Pull request by langwatch-agent**
## Ticket

Closes #521.

## Change

Every cucumber-bound suite resolved `specs/voice-agents.feature` by counting hops back to the repository root. The count depends on how deep the suite sits, so `src/voice/__tests__` needed four `".."` and `src/agents/judge/__tests__` needed five, and each file carried its own copy of an answer that is only correct where that file happens to live. Moving a test breaks its path; moving `specs/` means finding every copy.

`javascript/src/__tests__/features.ts` now anchors on its own location and exports `VOICE_AGENTS_FEATURE`, so the depth is a property of one file. The 22 suites import it and drop their `HERE` constant and their `node:path` / `node:url` imports where nothing else used them.

The helper also refuses a path that is not there. `loadFeature` on a missing file fails with a parse error quoting a path assembled from hops, which reads like a corrupt feature file rather than a moved one; the guard says which file is missing and where it looked.

The ticket counted four such files when it was filed. It is 22 now, which is the argument for doing it rather than against.

## Scope note

Two things in the diff beyond the mechanical swap, both worth knowing before reading it:

- **`javascript/src/__tests__/` is new.** The ticket suggested `javascript/src/voice/__tests__/_helpers.ts`, but the consumers are not all under `voice/` (there are suites in `agents/`, `agents/judge/` and `script/`), so the helper sits where all of them can reach it. `tsup` builds from explicit entries, so nothing here enters the published package.
- **11 pre-existing `import/order` violations got fixed.** `eslint --fix` was run on the touched files to clear the ordering the new import introduced, and it also tidied violations already on `main` in those same files. That is why a few diffs move imports the change did not otherwise touch.

## Evidence

**Full suite green.** `vitest run`: **1082 passed | 4 skipped (1086)**, 93 files. Every one of the 22 rewritten suites still loads and binds its scenarios.

**No new lint.** Compared rule-by-rule and file-by-file against `origin/main` using `eslint -f json`:

```
main:   209 problems
branch: 198 problems
NEW:      0
REMOVED: 11   (import/order, all pre-existing, in files this PR already touches)
```

**Typecheck unchanged.** `tsc --noEmit` output is byte-identical to `main`'s: both exit 2 on the same pre-existing `TS2688: Cannot find type definition file for 'yauzl'`, which this change neither causes nor fixes.

**Mutation-checked.** Four mutations of the new helper, restoring the file between runs:

| # | Mutation | Result |
|---|---|---|
| M1 | one hop short, resolves inside `javascript/` | CAUGHT (guard throws on import) |
| M2 | one hop long, resolves above the repository | CAUGHT (guard throws on import) |
| M3 | one hop short **and** the guard deleted | CAUGHT (3 failed) |
| M4 | resolves a different, real spec file | CAUGHT (1 failed) |

M3 is the one that earns the third assertion. With the guard gone the path simply points at a file that is not there, and it is `expect(VOICE_AGENTS_FEATURE).not.toContain("/javascript/")` that names the cause as "one hop short" rather than "missing file".

One harness note, since it changes how the table should be read: my first run reported M3 as ESCAPED. It had not escaped. The parser only matched a vitest summary containing the word `passed`, and M3 fails all three tests, so the line reads `Tests  3 failed (3)` and matched nothing, which scored as zero failures. Fixed to parse failed and passed independently and to report an unparseable run as INVALID rather than as a pass.

---

Advisory PR from the tech-debt-fixer bot, for human review, not to be merged by the bot.

### CODE REVIEW

File: javascript/src/__tests__/features.test.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+      // land on. Read it and check it is the feature the suites bind to.
+      expect(basename(VOICE_AGENTS_FEATURE)).toBe("voice-agents.feature");
+      expect(readFileSync(VOICE_AGENTS_FEATURE, "utf8")).toContain("Feature:");
+    });
+
+    it("resolves out of the javascript package, not inside it", () => {
+      // The hop count is the thing that was duplicated 22 times and the thing
+      // most likely to go wrong. specs/ sits at the repository root, above
+      // javascript/, so a path still inside the package means one hop short.
+      expect(VOICE_AGENTS_FEATURE).not.toContain("/javascript/");
```
[the remark this answers is not in the document]
Comment (langwatch-agent) [reply javascript/src/__tests__/features.test.ts]: Correct, fixed in `a083c61b`. `path.resolve` separates with a backslash on Windows, so the literal `"/javascript/"` could never match there and the assertion would have passed on exactly the platform where the path is most likely to be wrong. It now splits on `sep` and checks for a `javascript` segment, which means the same thing on both.

Re-verified: 3/3 on the guard file, eslint clean, and all four mutations of the helper still caught, including the one this assertion exists for (one hop short with the existence guard removed, which is the case where the path resolves to a real-looking location inside the package).

**Comment by langwatch-agent** [comment]
On the red `ci-checks (24.x)`: the one failing test is `javascript/examples/vitest/tests/scenario-expert-realtime.test.ts > should handle voice-to-voice conversation about Scenario framework`, failing on `expect(result.success).toBe(true)` at line 149. Everything else was green (33 files passed, 65 tests passed).

I do not believe it is this PR, and here is the basis rather than an assertion:

- This diff touches no file under `javascript/examples/`. Every change is under `javascript/src/**/__tests__/` plus the new `src/__tests__/` helper, none of which any example imports.
- The new helper is not in `tsup`'s entry list, so `buildpack` does not bundle it into the package the examples install. The examples' build step succeeded, which is consistent with that.
- The failing assertion is a live voice-to-voice round trip against the OpenAI Realtime API, judged by a model. That is a network and model dependent check, which is the profile of a flake rather than of a path-resolution change.

The push of `a083c61b` re-runs the job, so the next result is also the re-test. If it fails again in the same place I will stop treating it as a flake and dig in properly rather than repeat this reasoning.

**Comment by langwatch-agent** [comment]
Correcting my previous comment. I called this a flake; that was premature, and the re-run failed in exactly the same place, so I dug in as promised.

**The branch is not the cause, and this is now proven rather than argued.** I built the package on this branch and on `origin/main` and hashed the output:

```
tsup --no-dts, sha256 over all of dist/
branch: cad4e921bcf05abdb5065b6e348c6835dab7ac6c43a96e4a61b8c60b1ea950b7
main:   cad4e921bcf05abdb5065b6e348c6835dab7ac6c43a96e4a61b8c60b1ea950b7
```

Byte-identical. The examples install the tarball built from that `dist`, so they run identical code with or without this PR.

**But it is probably not a flake either, and my earlier reasoning was weak in a second way.** I said other open PRs were green on `ci-checks`. They are, but every one of those runs is from Aug 3 to Aug 5, and nothing has exercised this job since, so that told me nothing about today. Two consecutive failures at the same assertion points at something that moved outside the repository. The agent runs on `gpt-realtime`, an alias rather than a pinned snapshot, and the assertion is an LLM judge's verdict on a live voice conversation.

Filed as #882 with the evidence, including the one gap I could not close: I have not run the test against a clean `main` checkout, because it needs a realtime-capable credential I do not have here. That is the next step and would settle the model-drift reading.

This PR is otherwise green and its own suite is 1082 passing. Leaving the red visible rather than papering over it.

**Review by langwatch-agent — COMMENTED** [review]
Static review complete — no blocking findings.

The shared helper resolves `specs/voice-agents.feature` from its own stable location, all affected cucumber suites now use it, and the focused tests cover existence, feature identity, and the common one-hop-short regression. I treated `ci-checks (24.x)` as the already-tracked unrelated live-API example failure in #882, not a regression from this diff.

**Review by drewdrewthis — COMMENTED** [review]
Reviewed at `47ee0052`. No blocking findings.

The change is right and the shape is right. Twenty-two copies of a hop count that is only correct where each file happens to sit is exactly the kind of duplication that fails silently on a move, and anchoring on one module's own location is the fix. I walked every import site in the diff: the depths are all correct for where each suite lives, three hops from `voice/__tests__` and `agents/__tests__`, four from `judge/__tests__` and `adapters/__tests__`.

Putting the helper at `src/__tests__/` rather than the ticket's suggested `src/voice/__tests__/_helpers.ts` is the correct call and you gave the reason: four of the consumers are not under `voice/`.

The existence guard is the part that earns its keep. `loadFeature` on a missing file surfaces as a parse error quoting a path nobody wrote, which reads like a corrupt feature rather than a moved directory. Naming the file and the anchor turns a confusing failure into an obvious one.

The harness correction is worth calling out. A parser that only matched a summary containing `passed` scored a fully failing run as zero failures, so a caught mutation reported as ESCAPED. That is the same failure class as a guard that permits when its query errors: the check had no way to distinguish "nothing failed" from "I could not read the result". Reporting an unparseable run as INVALID rather than as a pass is the right correction, and finding it at all is the reason to trust the rest of the table.

Two notes, neither blocking.

1. **The segment check can still fail on an innocent checkout.** `VOICE_AGENTS_FEATURE.split(sep)` not containing `javascript` fixed the Windows half of coderabbit's point, since the literal `"/javascript/"` could never match there. The other half is still open: a clone under any directory named `javascript`, say `~/javascript/scenario`, puts that segment in the resolved path and the assertion fails on a correct resolution. The `relative`-against-package-root form suggested in that thread does not have this property. Low likelihood, and the cost is a confusing red test rather than a missed bug, so this is a note and not a request.

2. **`features.ts` throws at module load**, because `featurePath` runs at the top level. That is deliberate and I think correct, but it does mean a missing or moved spec fails all 23 suites at collection time rather than inside one test. Loud is what you want here; recording it so the blast radius is not a surprise.

On the mixed-in `eslint --fix`: folding 11 pre-existing `import/order` violations into this diff makes it noisier than the mechanical swap alone, but you disclosed it in the description with the reason, and the rule-by-rule comparison against `origin/main` (209 to 198, 0 new, 11 removed) is the right way to prove it added nothing.

Not claimed: I did not run vitest, eslint or `tsc`, and I did not reproduce the mutations. I read the diff and checked every import path against the directory each file lives in.

One process note: the `APPROVED` state here is the in-repo low-risk automation, not a human sign-off, and this PR says explicitly it is advisory and not to be merged by the bot.

**Comment by drewdrewthis** [comment]
## Review verdict: READY

Reviewed at `47ee0052a0477a60629c357dea891e3e3cf95426`.

No blocking findings.

Twenty-two copies of a hop count that is only correct where each file sits is duplication that fails silently on a move; anchoring on one module's own location is the fix. I walked every import site in the diff and the depths are all correct: three hops from `voice/__tests__` and `agents/__tests__`, four from `judge/__tests__` and `adapters/__tests__`.

Placing the helper at `src/__tests__/` rather than the ticket's `src/voice/__tests__/_helpers.ts` is correct, because four consumers are not under `voice/`.

The existence guard earns its keep: `loadFeature` on a missing file surfaces as a parse error quoting a path nobody wrote, which reads like a corrupt feature rather than a moved directory.

The harness correction is the most valuable disclosure here. A parser matching only a summary containing `passed` scored a fully failing run as zero failures, so a caught mutation reported as ESCAPED. Same failure class as a guard that permits when its query errors: no way to tell "nothing failed" from "I could not read the result". Reporting an unparseable run as INVALID is the right fix.

Non-blocking:

1. **The segment check can fail on an innocent checkout.** The `sep` split fixed the Windows half of coderabbit's point. A clone under any directory named `javascript`, for example `~/javascript/scenario`, still puts that segment in the resolved path and fails a correct resolution. The `relative`-against-package-root form does not have this property. Cost is a confusing red test, not a missed bug.
2. **`features.ts` throws at module load**, so a missing spec fails all 23 suites at collection rather than inside one test. Deliberate and correct; recorded so the blast radius is not a surprise.

The mixed-in `eslint --fix` of 11 pre-existing `import/order` violations makes the diff noisier, but it was disclosed with a reason and the rule-by-rule comparison against `origin/main` (209 to 198, 0 new, 11 removed) proves it added nothing.

Not claimed: I did not run vitest, eslint or `tsc`, and did not reproduce the mutations. Static read plus a per-file check of every import depth.

The `APPROVED` state on this PR is the in-repo low-risk automation, not a human sign-off, and the PR says it is advisory and not to be merged by the bot.
